---
name: "dioptra-github"

services:

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: dioptra
      POSTGRES_USER: dioptra
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '127.0.0.1:12432:5432'
    healthcheck:
      test: pg_isready -U dioptra -d dioptra
      start_interval: 1s
      start_period: 2s
    expose:
      - '12432'

  transaction_db:
    image: postgres:17
    environment:
      POSTGRES_DB: dioptra_transactions
      POSTGRES_USER: dioptra
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '127.0.0.1:9005:5432'
    healthcheck:
      test: pg_isready -U dioptra -d dioptra_transactions
      start_interval: 1s
      start_period: 2s
    expose:
      - '9005'
